katalog/urls.py
# TODO: Implement Routings Here
# jelasin
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, tambah_input, hapus_input, cheklist_todolist, registrasi, login_user, logout_user, show_json, add_task_ajax
app_name = "todolist"
urlpatterns = [
    path('', show_todolist, name="show_todolist"),
    path('create-task/', tambah_input, name="create-task"),
    path('hapus/<int:pk>', hapus_input, name="hapus"),
    path('cheklist/<int:pk>', cheklist_todolist, name="cheklist"), #update
    path('register/', registrasi, name="register"),
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),
    path('json/', show_json, name='show_json'),
    path('add/', add_task_ajax, name='add_task')
] 

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class BarangTodolist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.TextField()
    description = models.TextField()
    status = models.BooleanField(default=False)

todolist/views.py
from this import d
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from todolist.models import BarangTodolist
import datetime

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    context = { 
        "nama": request.user,
    }
    return render(request, "todolist.html", context)

# create function to show json
@login_required(login_url='/todolist/login/')
def show_json(request):
    todolist_data = BarangTodolist.objects.filter(user=request.user)
    
    return HttpResponse(serializers.serialize("json", todolist_data), content_type='application/json')

@login_required(login_url='/todolist/login/')
def tambah_input(request):
    context = {}
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        user = request.user
        data = BarangTodolist(user=user, title=title, description=description,  date=datetime.datetime.today())    
        data.save()
        return redirect("todolist:show_todolist")
    return render(request, "create-task.html", context)

@login_required(login_url='/todolist/login/')
def hapus_input(request, pk):
    # data = BarangTodolist.objects.filter(pk=pk)
    # data.delete()
    # return redirect("todolist:show_todolist")
    if request.method == "DELETE":
        data = BarangTodolist.objects.get(user=request.user,pk=pk)
        data.delete()
        return JsonResponse(
            {
                "pk": data.pk,
                "fields": {
                "title": data.title,
                "description": data.description,
                "status": data.status,
                "date": data.date,
                },

            },
            status=200,
        )

def cheklist_todolist(request, pk):
    if request.method == "PUT":
        data = BarangTodolist.objects.get(user=request.user,pk=pk)
        data.status = not data.status
        data.save()
        return JsonResponse(
            {
                "pk": data.pk,
                "fields": {
                "title": data.title,
                "description": data.description,
                "status": data.status,
                "date": data.date,
                },

            },
            status=200,
        )

def registrasi(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registration successful")
            return redirect("todolist:login")
    context = {"form":form}
    return render(request, "register.html", context)

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.warning(request, "Username OR password is incorrect")
    context = {}
    return render(request, "login.html", context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def add_task_ajax(request):
    if request.method ==  "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        user = request.user
        data = BarangTodolist.objects.create(user=user, title=title, description=description, date=datetime.datetime.today())    
        return JsonResponse({
            "pk": data.pk,
            "fields": {
                "title": data.title,
                "description": data.description,
                "status": data.status,
                "date": data.date,
            },
        },
        status=200,
        )

todolist/templates/create-task.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div class="px-8 py-6 mt-4 text-left bg-white shadow-lg">
      <h3 class="text-2xl font-bold text-center">Create Task</h3>
      <form action="" method="POST">
          {% csrf_token %}
          <div class="mt-4">
              <div>
                <td>Tittle: </td>
                          <input type="text" name="title" placeholder="TITTLE"
                              class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600 form-control">
              </div>
              <div class="mt-4">
                <td>Description: </td>
                  <input ttype="text" name="description" placeholder="DESCRIPTION"
                      class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600 form-control">
              </div>
              {% comment %} add new line for space login and text cnter {% endcomment %}
              <div class="mt-4">
                <input
                data-mdb-ripple="true"
                data-mdb-ripple-color="light"
                class="btn login_btn w-full px-4 py-2 text-white rounded md bg-gradient-to-r from-blue-500 to-red-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
                type="submit"
                value="Submit"
                href="{% url 'todolist:show_todolist' %}"
              />
 
          </div>
      </form>
      
  </div>
</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div class="px-8 py-6 mt-4 text-left bg-white shadow-lg">
      <h3 class="text-2xl font-bold text-center">Login</h3>
      <form action="" method="POST">
          {% csrf_token %}
          <div class="mt-4">
              <div>
                  <label class="block" for="username">Username<label>
                          <input type="text" name="username" placeholder="Username"
                              class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
              </div>
              <div class="mt-4">
                  <label class="block" for="password">Password<label>
                  <input type="password" placeholder="Password" name="password"
                      class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
              </div>
              {% comment %} add new line for space login and text cnter {% endcomment %}
              <div class="mt-4">
                <input
                data-mdb-ripple="true"
                data-mdb-ripple-color="light"
                class="w-full px-4 py-2 text-white rounded md bg-gradient-to-r from-blue-500 to-red-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
                type="submit"
                value="Login"
              />
 
          </div>
      </form>
      {% if messages %}
      <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <p> 
        Belum mempunyai akun?
        <a href="{% url 'todolist:register' %}" class="font-bold text-blue-600 underline hover:underline rounded-md">Buat Akun</a>
      </p> 
  </div>
</div>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %} {% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %} {% block content %}

<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div class="px-12 py-10 mt-4 text-left bg-blue-lg">
      <h3 class="text-2xl font-bold text-center">Registration Form</h3>
      <form action="" method="POST">
          {% csrf_token %}
          <table class="border-separate border-spacing-2 border border-slate-500">  
            {{ form.as_table }}  
            <tr>  
                <td></td>
                <td><input class="bg-gradient-to-r from-blue-500 to-red-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" type="submit" name="submit" value="Daftar"/></td>  
            </tr>  
            <td>
              Sudah mempunyai akun?
              <a
                href="{% url 'todolist:login' %}"
                class="font-bold text-blue-600 underline hover:bg-gradient-to-bl"
                >Login</a
              >
            </td>
        </table>  
      </form>
      
      {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/registration.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login" style="margin-left: auto; margin-right: auto;"> 
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %} {% block content %} {% load todolist_customtags %}

<script>
  $(document).ready(() => {
    const card = data => `
      <div
        class="card flex justify-center ${
          data.fields.status && "opacity-50"
        } hover:scale-105 transition-all"
      >
        <div
          class="block rounded-lg shadow-lg hover:shadow-blue-500/30 bg-white max-w-sm text-center w-80"
        >
          <div
            class="py-3 px-6 border-b bg-gray-800 ${
              data.fields.status
                ? "bg-gradient-to-r from-green-400 to-green-600"
                : "from-purple-600 to-blue-500"
            } flex gap-4 text-white justify-center form-check items-center rounded-t-lg hover:bg-gradient-to-bl transition-all"
          >
            <label for="status inline-block">Finished?</label>
            <input
              type="checkbox"
              name="status"
              id="status-${data.pk}"
              ${data.fields.status && "checked"}
              class="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 focus:ring-2"
            />
          </div>
          <div class="p-6">
            <h5 class="text-gray-900 text-xl font-bold mb-2">${
              data.fields.title
            }</h5>
            <p class="text-gray-700 text-sm mb-4">${data.fields.description}</p>
            <button
              id="delete-${data.pk}"
              type="button"
              class="inline-block mx-auto hover:shadow-lg hover:shadow-blue-500/50 px-6 pt-2.5 pb-2 transition duration-150 ease-in-out flex align-center gap-2 items-center text-white bg-gradient-to-r from-blue-500 to-red-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 rounded-lg px-5 py-2.5"
            >
              Delete
            </button>
          </div>
          <div class="py-3 px-6 border-t border-gray-300 text-gray-600">
            <p class="text-xs">Created At:</p>
            <p>${data.fields.date}</p>
          </div>
        </div>
      </div>
    `;

    const renderTasks = () => {
      // fetching the tasks
      $.get("{% url 'todolist:show_json' %}", data => {
        data.sort((a, b) => {
          return a.fields.status - b.fields.status;
        });
        $.each(data, (i, value) => {
          $("#todolist").append(card(value)); // append to the div

          // add event listener to the delete button
          $(`#delete-${value.pk}`).click(() => {
            deleteTask(value.pk);
          });

          // add event listener to the checkbox
          $(`#status-${value.pk}`).change(() => {
            Cheklist(value.pk);
          });
        });
      });
    };

    const deleteTask = id => {
      // get the CSRF Token
      const csrftoken = document.querySelector(
        "[name=csrfmiddlewaretoken]"
      ).value;

      $.ajax({
        url: "{% url 'todolist:hapus' 0 %}".replace("0", id),
        type: "DELETE",
        headers: { "X-CSRFToken": csrftoken }, // give CSRF token to the header
        mode: "same-origin", // Do not send CSRF token to another domain.
        success: () => {
          // remove the card
          $(`#delete-${id}`).parent().parent().parent().remove();
        },
        error: error => {
          console.log(error);
        },
      });
    };

    const Cheklist = id => {
      // get the CSRF Token
      const csrftoken = document.querySelector(
        "[name=csrfmiddlewaretoken]"
      ).value;

      $.ajax({
        url: "{% url 'todolist:cheklist' 0 %}".replace("0", id),
        type: "PUT",
        headers: { "X-CSRFToken": csrftoken }, // give CSRF token to the header
        mode: "same-origin", // Do not send CSRF token to another domain.
        success: response => {
          // refresh
          $("#todolist").empty();
          renderTasks();
        },
        error: error => {
          console.log(error);
        },
      });
    };

    const openModal = e => {
      e.preventDefault(); // prevent refresh
      $("#create-data-modal").removeClass("hidden");
    };

    const closeModal = e => {
      // e.preventDefault(); // prevent refresh
      $("#create-data-modal").addClass("hidden");
    };

    $("#create-data-form").submit(e => {
      e.preventDefault();

      // get the CSRF Token
      const csrftoken = document.querySelector(
        "[name=csrfmiddlewaretoken]"
      ).value;

      const title = $("#title").val();
      const description = $("#description").val();

      if (title && description) {
        $.ajax({
          type: "POST",
          url: "{% url 'todolist:add_task' %}",
          headers: { "X-CSRFToken": csrftoken }, // give CSRF token to the header
          mode: "same-origin", // Do not send CSRF token to another domain.
          data: {
            title: title,
            description: description,
          },
          success: response => {
            $("#create-data-form").trigger("reset");
            closeModal();
            $("#todolist").prepend(card(response));
          },
          error: error => {
            console.log(error);
          },
        });
      } else {
        alert("Please fill all the fields");
      }
    });

    $("#create-data").click(openModal);
    $("#close-modal").click(closeModal);

    renderTasks(); // render the tasks to the page
  });
</script>

{% comment %} MODAL {% endcomment %}
<div
  id="create-data-modal"
  class="w-full fixed flex justify-center w-full z-10 min-h-screen items-center bg-black bg-opacity-50 hidden"
>
  <div class="mt-7 bg-white rounded-xl shadow-lg">
    <div class="p-4 sm:p-7">
      <div class="flex flex-col items-center justify-center gap-5">
        <h1 class="text-3xl font-bold">Create Task</h1>
        <form method="post" id="create-data-form">
          {% csrf_token %}
          <div class="gap-5 text-left grid grid-cols-3 grid-rows-3">
            <label for="title">Title:</label>
            <input
              type="text"
              name="title"
              id="title"
              placeholder="Isi judul data anda"
              required
              class="col-span-2 form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
            />

            <label for="password">Description:</label>
            <input
              type="text"
              name="description"
              id="description"
              placeholder="Isi deskripsi anda"
              required
              class="col-span-2 form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
            />

            <input
              data-mdb-ripple="true"
              data-mdb-ripple-color="light"
              class="col-span-3 text-white hover:shadow-lg hover:shadow-blue-500/50 transition-all bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
              type="submit"
              value="Create Task"
            />
          </div>
        </form>
        <a
          href="{% url 'todolist:show_todolist' %}"
          class="font-bold text-blue-600 underline hover:no-underline"
          id="close-modal"
          >Close</a
        >
      </div>
    </div>
  </div>
</div>

{% comment %} <div
  class="space-y-5 md:space-y-10 pt-10 max-w-[80%] mx-auto min-h-screen text-center"
> {% endcomment %}
<nav class="font-sans flex flex-col text-center sm:flex-row sm:text-left sm:justify-between py-4 px-6 bg-white shadow sm:items-baseline w-full">
  <div class="mb-2 sm:mb-0">
    <h1 class="text-2xl font-bold">Welcome back, <span class="text-blue-500">{{ nama }}</span>!</h1>
  </div>
  <div>
    <button
    onclick="location.href='{% url 'todolist:logout' %}'"
    type="button"
    class="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white focus:ring-4 focus:outline-none focus:ring-pink-200"
  >
    <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white rounded-md group-hover:bg-opacity-0">Logout</span>
  </button>
  </div>
</nav>
<div class="space-y-5 md:space-y-10 pt-10 max-w-[80%] mx-auto min-h-screen text-center">
  <button
    type="button"
    class="inline-block mx-auto hover:shadow-lg hover:shadow-blue-500/50 px-6 pt-2.5 pb-2 transition duration-150 ease-in-out flex align-center gap-2 items-center text-white bg-gradient-to-r from-blue-500 to-red-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 rounded-lg px-5 py-2.5"
    id="create-data"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-6 h-6"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
    <p>Create Task</p>
  </button>

  <div class="flex flex-wrap gap-20 justify-center pb-20" id="todolist"></div>
</div>

{% endblock content %}